version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # api:
  #   build: .
  #   environment:
  #     PGUSER: postgres
  #     PGPASSWORD: postgres
  #     PGDATABASE: postgres
  #     PGHOST: postgres
  #     PGPORT: 5432
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
